security:
  oauth2:
    client:
      clientId: 198659840500311
      clientSecret: 97d6fc7c788463e2de89f1571385cc75
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
      spring.resources.chain.enabled: true